namespace Catel.SourceGenerators.XamlConstructors;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class GenerateEmptyConstructorAttributeSourceGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Catel
        {
            using System;

            /// <summary>
            /// Marks a class so that a source generator will generate an empty (parameterless) constructor
            /// and the static <c>GetService&lt;T&gt;</c> helper for dependency injection at runtime.
            /// The class must be declared as <c>partial</c>.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class GenerateEmptyConstructorAttribute : Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateEmptyConstructorAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
        });
    }
}
