namespace Catel.SourceGenerators.XamlConstructors;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class InjectedServiceAttributeSourceGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Catel
        {
            using System;

            /// <summary>
            /// Marks a readonly field as a dependency to be injected by the source generator.
            /// The generator will create a constructor parameter for this field and initialize it
            /// in the generated constructor body.
            /// </summary>
            [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
            internal sealed class InjectedServiceAttribute : Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("InjectedServiceAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
        });
    }
}
