namespace Catel.SourceGenerators.XamlConstructors
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    [Generator]
    public class InjectedModelAttributeSourceGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = """
            // <auto-generated/>
            #nullable enable

            namespace Catel
            {
                using System;

                /// <summary>
                /// Marks a field or property as the model to be injected via the constructor
                /// generated by the source generator for ViewModelBase-derived classes.
                /// Only one member per class may carry this attribute.
                /// The decorated member will be assigned in the generated constructor before any
                /// injected services are assigned.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
                internal sealed class InjectedModelAttribute : Attribute
                {
                }
            }
            """;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("InjectedModelAttribute.g.cs",
                    SourceText.From(AttributeSource, Encoding.UTF8));
            });
        }
    }
}
