//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("CatenaLogic")]
[assembly: AssemblyVersion("7.0.1")]
[assembly: AssemblyFileVersion("7.0.1")]
[assembly: AssemblyInformationalVersion("7.0.1-alpha.5")]
[assembly: AssemblyCopyright("Copyright © CatenaLogic 2019 - 2025")]

