//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("CatenaLogic")]
[assembly: AssemblyVersion("7.1.0")]
[assembly: AssemblyFileVersion("7.1.0")]
[assembly: AssemblyInformationalVersion("7.1.0-alpha.80")]
[assembly: AssemblyCopyright("Copyright © CatenaLogic 2019 - 2026")]

